Added action-classes
htmlacademy-yii/234035-task-force-1 pull request #5
Opened 2020-09-01 11:16 UTC by kobrikov

2020-09-02 21:40 UTC, runtothefather requested changes

2020-09-02 21:40 UTC, runtothefather commented on src/CancelAction.php
> +        return $this->actionName;
поле не нужно в принципе, можно возвращать прямо здесь строку

2020-09-02 21:40 UTC, runtothefather commented on src/CancelAction.php
> +namespace TaskForce;
стоит передвинуть экшины в отдельную папку, например src/Actions

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +    public const STATUS_NEW = 'new status'; //новое
такие комментарии лучше не писать, в данном случае они информативности не добавляют, а мозг всё равно их читает

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +    public function __construct($customerID, $executorID, $userID)
типы аргументов

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +        if ($status == 'new status') {
всегда лучше использовать строгое стравнение (===)

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +        return $result;
а что если пришёл статус не work и не new?

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +    public function getActions(string $status): object
лучше указать тип абстрактного класса

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +    private $customerID = null;
если используешь пхп 7.4 то сюда типы тоже стоит писать, инициализировать налом не нужно

2020-09-02 21:40 UTC, runtothefather commented on src/Task.php
> +        if ($status == 'work status') {
сравнить лучше с константой статуса которая уже есть

2020-09-07 10:51 UTC, kobrikov commented on src/CancelAction.php
> +        return $this->actionName;
fixed

2020-09-07 11:25 UTC, kobrikov commented on src/CancelAction.php
> +namespace TaskForce;
fixed

2020-09-07 11:27 UTC, kobrikov commented on src/Task.php
> +    public function __construct($customerID, $executorID, $userID)
fixed

2020-09-07 11:27 UTC, kobrikov commented on src/Task.php
> +        if ($status == 'new status') {
fixed

2020-09-07 11:37 UTC, kobrikov commented on src/Task.php
> +    public function getActions(string $status): object
fixed

2020-09-07 12:09 UTC, kobrikov commented on src/Task.php
> +    private $customerID = null;
fixed

2020-09-07 12:13 UTC, kobrikov commented on src/Task.php
> +    public const STATUS_NEW = 'new status'; //новое
fixed

2020-09-07 12:49 UTC, kobrikov commented on src/Task.php
> +        return $result;
выбросил исключение

2020-09-07 12:54 UTC, kobrikov commented on src/Task.php
> +        if ($status == 'work status') {
fixed

2020-09-07 15:48 UTC, runtothefather approved these changes

2020-09-07 15:49 UTC, merged